In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('/home/ubuntu/VGG-Face2/hurtlex_EN.tsv', sep='\t', )

In [3]:
df

          id pos category stereotype           lemma         level
0     EN1382   n      qas         no        gag reel     inclusive
1     EN7077   a      cds         no          snotty  conservative
2     EN6856   n       is        yes       mendicant  conservative
3     EN5485   n       re         no         maffias  conservative
4     EN5024   n      cds         no  lying in trade  conservative
...      ...  ..      ...        ...             ...           ...
8223  EN7899   n       an         no      perosuchus     inclusive
8224  EN1319   n      cds         no    mother fucka  conservative
8225  EN2597   n      cds         no          refuse  conservative
8226   EN521   n      asm         no          simple     inclusive
8227   EN195   a       an         no        stubborn     inclusive

[8228 rows x 6 columns]

In [6]:
df.groupby('category').count()

            id   pos  stereotype  lemma  level
category
an         996   996         996    996    996
asf        144   144         144    144    144
asm        426   426         426    426    426
cds       2204  2204        2204   2204   2204
ddf         63    63          63     63     63
ddp        491   491         491    491    491
dmc        715   715         715    715    715
is         124   124         124    124    124
om         361   361         361    361    361
or         177   177         177    177    177
pa         192   192         192    192    192
pr         276   276         276    276    276
ps         371   371         371    371    371
qas        518   518         518    518    518
rci         24    24          24     24     24
re         619   619         619    619    619
svp        527   527         527    527    527